"""initialize

Revision ID: 4246b114aa22
Revises: 
Create Date: 2024-11-14 19:01:53.627752

"""
from typing import Sequence, Union
from datetime import datetime
import hashlib

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column


# revision identifiers, used by Alembic.
revision: str = '4246b114aa22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )

    # Insert default superuser
    users = table(
        'users',
        column('email', sa.String),
        column('username', sa.String),
        column('password', sa.String),
        column('is_active', sa.Boolean),
        column('is_superuser', sa.Boolean),
        column('created_at', sa.DateTime),
        column('updated_at', sa.DateTime)
    )

    op.bulk_insert(users, [
        {
            'email': 'noiphap@gmail.com',
            'username': 'admin',
            'password': hashlib.sha512('admin'.encode()).hexdigest(),
            'is_active': True,
            'is_superuser': True,
            'created_at': datetime.now(),
            'updated_at': datetime.now()
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
