"""create super user

Revision ID: 55a13fafd082
Revises: 91203f3d9558
Create Date: 2024-11-14 20:19:57.318063

"""
from datetime import datetime
import hashlib
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a13fafd082'
down_revision: Union[str, None] = '91203f3d9558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Insert default superuser
    users = sa.table(
        'users',
        sa.column('id', sa.UUID),
        sa.column('email', sa.String),
        sa.column('username', sa.String),
        sa.column('password', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('is_superuser', sa.Boolean),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime)
    )

    op.bulk_insert(users, [
        {
            'id': str(uuid4()),
            'email': 'noiphap@gmail.com',
            'username': 'admin',
            'password': hashlib.sha512('admin'.encode()).hexdigest(),
            'is_active': True,
            'is_superuser': True,
            'created_at': datetime.now(),
            'updated_at': datetime.now()
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
