"""
This type stub file was generated by pyright.
"""

from mongoengine import connection, document, errors, fields, queryset, signals
from mongoengine.connection import *
from mongoengine.document import *
from mongoengine.errors import *
from mongoengine.fields import *
from mongoengine.queryset import *
from mongoengine.signals import *

__all__ = (list(document.__all__) + list(fields.__all__) + list(connection.__all__) + list(queryset.__all__) + list(signals.__all__) + list(errors.__all__))
VERSION = ...
def get_version(): # -> str:
    """Return the VERSION as a string.

    For example, if `VERSION == (0, 10, 7)`, return '0.10.7'.
    """
    ...

__version__ = ...
