"""
This type stub file was generated by pyright.
"""

"""
Helper functions, constants, and types to aid with PyMongo support.
"""
PYMONGO_VERSION = ...
if PYMONGO_VERSION >= (4, ):
    LEGACY_JSON_OPTIONS = ...
else:
    LEGACY_JSON_OPTIONS = ...
def count_documents(collection, filter, skip=..., limit=..., hint=..., collation=...): # -> Any | Literal[0]:
    """Pymongo>3.7 deprecates count in favour of count_documents"""
    ...

def list_collection_names(db, include_system_collections=...): # -> list[Any]:
    """Pymongo>3.7 deprecates collection_names in favour of list_collection_names"""
    ...

