"""initialize

Revision ID: a5aacc23cffa
Revises: 
Create Date: 2024-11-14 18:33:47.945276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5aacc23cffa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'username',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'password',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'is_active',
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'is_superuser',
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'created_by',
            sa.INTEGER(),
            autoincrement=False,
            nullable=True
        ),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False
        ),
        sa.Column(
            'updated_by',
            sa.INTEGER(),
            autoincrement=False,
            nullable=True
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False
        ),
        sa.PrimaryKeyConstraint('id', name='users_pkey'),
        sa.UniqueConstraint('email', name='users_email_key'),
        sa.UniqueConstraint('username', name='users_username_key')
    )
    # ### end Alembic commands ###
