"""
This type stub file was generated by pyright.
"""

__all__ = ("UPDATE_OPERATORS", "get_document", "_document_registry")
UPDATE_OPERATORS = ...
_document_registry = ...
def get_document(name):
    """Get a registered Document class by name."""
    ...

