"""
This type stub file was generated by pyright.
"""

class LazyRegexCompiler:
    """Descriptor to allow lazy compilation of regex"""
    def __init__(self, pattern, flags=...) -> None:
        ...
    
    @property
    def compiled_regex(self): # -> Pattern[Any]:
        ...
    
    def __get__(self, instance, owner): # -> Pattern[Any]:
        ...
    
    def __set__(self, instance, value):
        ...
    


